sonar.projectKey=Pratibhajha2968_Job_Portal_Frontend
sonar.organization=pratibhajha2968
sonar.projectName=Job Portal Frontend

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.min.js
sonar.sourceEncoding=UTF-8
