// pages/JobsData.jsx
export const allJobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "XYZ Corp",
    location: "Bangalore",
    mode: "Remote",
    salary: "8 – 12 LPA",
    experience: "Fresher – 2 years",
    type: "Full-time",
    skills: ["React", "TailwindCSS", "JavaScript", "HTML", "CSS"],
    postedDate: "2026-01-20",
    description:
      "Work on building responsive web UIs using React and TailwindCSS. Collaborate with backend developers and designers to create seamless user experiences.",
    responsibilities: [
      "Develop responsive user interfaces",
      "Collaborate with backend team",
      "Write clean, maintainable code",
    ],
    requirements: [
      "Knowledge of React & JS",
      "CSS and HTML expertise",
      "Problem-solving skills",
    ],
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "ABC Ltd",
    location: "Hyderabad",
    mode: "Hybrid",
    salary: "10 – 15 LPA",
    experience: "2 – 4 years",
    type: "Full-time",
    skills: ["Node.js", "Express", "MongoDB", "SQL", "REST APIs"],
    postedDate: "2026-01-18",
    description:
      "Develop APIs using Node.js or Spring Boot. Work with databases and cloud infrastructure. Ensure performance and security standards are met.",
    responsibilities: [
      "Develop RESTful APIs",
      "Database integration",
      "Performance optimization",
    ],
    requirements: [
      "Node.js or Java experience",
      "Database knowledge (SQL/NoSQL)",
      "Understanding of cloud services",
    ],
  },
  {
    id: 3,
    title: "Full Stack Developer",
    company: "Tech Solutions",
    location: "Chennai",
    mode: "On-site",
    salary: "12 – 18 LPA",
    experience: "1 – 3 years",
    type: "Full-time",
    skills: ["React", "Node.js", "SQL", "NoSQL", "REST APIs"],
    postedDate: "2026-01-22",
    description:
      "Build full stack applications using React, Node.js, and SQL/NoSQL databases. Work closely with frontend and backend teams for seamless integration.",
    responsibilities: [
      "Develop frontend & backend",
      "Integrate databases",
      "Ensure smooth deployment",
    ],
    requirements: [
      "React & Node.js experience",
      "Database knowledge",
      "Problem-solving and debugging skills",
    ],
  },
  {
    id: 4,
    title: "UI/UX Designer",
    company: "Creative Minds",
    location: "Pune",
    mode: "Remote",
    salary: "6 – 10 LPA",
    experience: "Fresher – 2 years",
    type: "Full-time",
    skills: ["Figma", "Adobe XD", "User Research", "Wireframing"],
    postedDate: "2026-01-19",
    description:
      "Design creative user interfaces and experiences for web and mobile applications.",
    responsibilities: [
      "Create wireframes and mockups",
      "Design UI components",
      "User testing and feedback",
    ],
    requirements: [
      "UI/UX design knowledge",
      "Adobe XD or Figma skills",
      "Creativity and teamwork",
    ],
  },
  {
    id: 5,
    title: "Data Analyst",
    company: "Data Insights",
    location: "Bangalore",
    mode: "Hybrid",
    salary: "5 – 8 LPA",
    experience: "Fresher – 2 years",
    type: "Full-time",
    skills: ["Excel", "SQL", "Python", "Power BI"],
    postedDate: "2026-01-21",
    description:
      "Analyze business data, create dashboards and reports, and assist in data-driven decisions.",
    responsibilities: [
      "Analyze datasets",
      "Create visual dashboards",
      "Provide insights for management",
    ],
    requirements: ["SQL knowledge", "Excel & Python skills", "Analytical thinking"],
  },
  {
    id: 6,
    title: "DevOps Engineer",
    company: "CloudOps",
    location: "Mumbai",
    mode: "On-site",
    salary: "8 – 14 LPA",
    experience: "2 – 5 years",
    type: "Full-time",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    postedDate: "2026-01-20",
    description:
      "Manage CI/CD pipelines, deployment, and monitoring of applications in cloud environments.",
    responsibilities: [
      "Setup CI/CD pipelines",
      "Manage cloud infrastructure",
      "Monitor applications",
    ],
    requirements: ["AWS/Kubernetes knowledge", "Scripting skills", "Problem-solving"],
  },
  {
    id: 7,
    title: "Mobile App Developer",
    company: "AppWorks",
    location: "Bangalore",
    mode: "Remote",
    salary: "7 – 12 LPA",
    experience: "Fresher – 3 years",
    type: "Full-time",
    skills: ["React Native", "Flutter", "Android", "iOS"],
    postedDate: "2026-01-18",
    description:
      "Develop mobile applications using React Native or Flutter for Android and iOS platforms.",
    responsibilities: [
      "Build mobile apps",
      "Debug and test apps",
      "Collaborate with backend team",
    ],
    requirements: ["React Native/Flutter knowledge", "Mobile UI/UX skills", "Teamwork"],
  },
  {
    id: 8,
    title: "Machine Learning Engineer",
    company: "ML Labs",
    location: "Hyderabad",
    mode: "Hybrid",
    salary: "12 – 20 LPA",
    experience: "3 – 5 years",
    type: "Full-time",
    skills: ["Python", "TensorFlow", "PyTorch", "Data Preprocessing"],
    postedDate: "2026-01-17",
    description:
      "Implement ML models, perform data preprocessing, and collaborate with data scientists.",
    responsibilities: [
      "Develop ML models",
      "Data preprocessing",
      "Collaborate with data scientists",
    ],
    requirements: ["Python & ML libraries", "Math & Statistics", "Problem-solving"],
  },
  {
    id: 9,
    title: "Quality Assurance Engineer",
    company: "QA Experts",
    location: "Chennai",
    mode: "On-site",
    salary: "5 – 9 LPA",
    experience: "Fresher – 2 years",
    type: "Full-time",
    skills: ["Manual Testing", "Automation Testing", "Selenium", "JIRA"],
    postedDate: "2026-01-21",
    description:
      "Test web and mobile applications, write test cases, and report bugs effectively.",
    responsibilities: [
      "Manual & automation testing",
      "Write test cases",
      "Report bugs",
    ],
    requirements: ["Testing knowledge", "Attention to detail", "JIRA experience"],
  },
  {
    id: 10,
    title: "Cloud Engineer",
    company: "CloudWorks",
    location: "Bangalore",
    mode: "Remote",
    salary: "10 – 18 LPA",
    experience: "2 – 5 years",
    type: "Full-time",
    skills: ["AWS", "Azure", "Terraform", "Docker"],
    postedDate: "2026-01-19",
    description:
      "Design and manage cloud infrastructure, optimize costs, and implement security best practices.",
    responsibilities: [
      "Manage cloud services",
      "Optimize infrastructure",
      "Implement security best practices",
    ],
    requirements: ["AWS/Azure knowledge", "Infrastructure as Code", "Security awareness"],
  },
  {
    id: 11,
    title: "React Developer",
    company: "Frontend Masters",
    location: "Pune",
    mode: "Hybrid",
    salary: "8 – 14 LPA",
    experience: "Fresher – 3 years",
    type: "Full-time",
    skills: ["React", "Redux", "JavaScript", "HTML", "CSS"],
    postedDate: "2026-01-16",
    description:
      "Develop responsive web apps using React, Redux, and modern UI libraries.",
    responsibilities: [
      "Build responsive web apps",
      "State management using Redux",
      "Code reviews",
    ],
    requirements: ["React & Redux knowledge", "JavaScript skills", "Teamwork"],
  },
  {
    id: 12,
    title: "Node.js Developer",
    company: "Backend Pros",
    location: "Hyderabad",
    mode: "On-site",
    salary: "9 – 16 LPA",
    experience: "1 – 4 years",
    type: "Full-time",
    skills: ["Node.js", "Express", "MongoDB", "SQL"],
    postedDate: "2026-01-18",
    description:
      "Build RESTful APIs, integrate databases, and ensure application performance.",
    responsibilities: [
      "Develop APIs",
      "Integrate databases",
      "Optimize performance",
    ],
    requirements: ["Node.js/Express", "SQL/MongoDB", "Problem-solving"],
  },
  {
    id: 13,
    title: "Python Developer",
    company: "PyTech",
    location: "Bangalore",
    mode: "Remote",
    salary: "7 – 12 LPA",
    experience: "Fresher – 3 years",
    type: "Full-time",
    skills: ["Python", "Django", "Flask", "SQL"],
    postedDate: "2026-01-20",
    description:
      "Develop backend services, scripts, and automation using Python and Django/Flask.",
    responsibilities: [
      "Backend development",
      "Automation scripts",
      "Database integration",
    ],
    requirements: ["Python", "Django/Flask", "SQL knowledge"],
  },
  {
    id: 14,
    title: "Data Scientist",
    company: "Data Minds",
    location: "Mumbai",
    mode: "Hybrid",
    salary: "12 – 20 LPA",
    experience: "2 – 5 years",
    type: "Full-time",
    skills: ["Python", "R", "ML", "Deep Learning", "Statistics"],
    postedDate: "2026-01-21",
    description:
      "Analyze data, build predictive models, and collaborate with cross-functional teams.",
    responsibilities: [
      "Data analysis",
      "Model building",
      "Reporting insights",
    ],
    requirements: ["Python/R", "ML libraries", "Statistics & Math"],
  },
  {
    id: 15,
    title: "Software Engineer Intern",
    company: "TechStart",
    location: "Chennai",
    mode: "Remote",
    salary: "3 – 5 LPA",
    experience: "Fresher",
    type: "Internship",
    skills: ["JavaScript", "React", "Node.js"],
    postedDate: "2026-01-22",
    description:
      "Assist in software development tasks, bug fixing, and learning modern development tools.",
    responsibilities: [
      "Assist in development",
      "Debug code",
      "Learn modern tools",
    ],
    requirements: ["Basic JS/React/Node.js", "Eagerness to learn"],
  },
  {
    id: 16,
    title: "Java Developer",
    company: "JavaWorks",
    location: "Bangalore",
    mode: "On-site",
    salary: "9 – 15 LPA",
    experience: "1 – 3 years",
    type: "Full-time",
    skills: ["Java", "Spring Boot", "SQL"],
    postedDate: "2026-01-17",
    description:
      "Work on backend services using Java, Spring Boot, and RESTful APIs.",
    responsibilities: ["Backend development", "API creation", "Database integration"],
    requirements: ["Java/Spring Boot", "SQL", "Problem-solving"],
  },
  {
    id: 17,
    title: "Android Developer",
    company: "AppMakers",
    location: "Hyderabad",
    mode: "Remote",
    salary: "7 – 13 LPA",
    experience: "Fresher – 2 years",
    type: "Full-time",
    skills: ["Kotlin", "Java", "Android Studio"],
    postedDate: "2026-01-19",
    description:
      "Develop native Android apps using Kotlin/Java and integrate with REST APIs.",
    responsibilities: ["Build Android apps", "Integrate APIs", "Test apps"],
    requirements: ["Kotlin/Java knowledge", "Android Studio", "Debugging skills"],
  },
  {
    id: 18,
    title: "iOS Developer",
    company: "iOS Labs",
    location: "Pune",
    mode: "Hybrid",
    salary: "8 – 14 LPA",
    experience: "1 – 3 years",
    type: "Full-time",
    skills: ["Swift", "Xcode", "iOS SDK"],
    postedDate: "2026-01-18",
    description:
      "Develop iOS applications using Swift and maintain app performance and quality.",
    responsibilities: ["Develop iOS apps", "Debug and test apps", "Collaborate with team"],
    requirements: ["Swift/Xcode", "iOS SDK", "Problem-solving"],
  },
  {
    id: 19,
    title: "UI Developer",
    company: "Frontend Hub",
    location: "Chennai",
    mode: "Remote",
    salary: "6 – 10 LPA",
    experience: "Fresher – 2 years",
    type: "Full-time",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    postedDate: "2026-01-20",
    description:
      "Implement web interfaces using HTML, CSS, JavaScript, and frontend frameworks.",
    responsibilities: ["Build web pages", "Collaborate with designers", "Optimize UI"],
    requirements: ["HTML/CSS/JS", "React knowledge", "Creativity"],
  },
  {
    id: 20,
    title: "Business Analyst",
    company: "BizCorp",
    location: "Mumbai",
    mode: "On-site",
    salary: "5 – 9 LPA",
    experience: "Fresher – 3 years",
    type: "Full-time",
    skills: ["Excel", "SQL", "Power BI", "Reporting"],
    postedDate: "2026-01-22",
    description:
      "Gather business requirements, create reports, and assist in project management.",
    responsibilities: ["Requirement gathering", "Report creation", "Assist in PM"],
    requirements: ["Excel/SQL", "Analytical skills", "Communication skills"],
  },
];
